---
#- name: "Add server to in-memory inventory"
#  hosts: localhost
#  gather_facts: false  
#  tasks:
#    - name: "Add server to in-memory inventory group"
#      add_host:
#        name: "{{ server_to_patch }}"
#        groups: patch_all
        
- name: "Patching linux servers using ansible-linux-patch-post-checks roles"
  hosts: all
  gather_facts: True
  become: yes
  vars: 
    patching_type: "SYSTEM_UPDATE"
  roles:
    - ansible-linux-patch-yum.update

