---
   - name: Check available diskspace on / partition
     shell: df  /root --output\=avail | tail -1
     register: root_freespace

   - shell: echo "{{ inventory_hostname }}"
     register: op

   - debug:
       msg:
         - "{{ root_freespace.stdout }}"
         - "{{ op.stdout }}"

   - mail:
       subject: 'DISK USAGE ALERT !!!'
       from: 'OnyekachiA@aetna.com'
       body: "/root  HAS REACHED {{ root_freespace.stdout }}  ON {{ op.stdout }}, and does not have the minimum space required to continue (2Gb requested). KINDLY CHECK !!!"
       to: 'OnyekachiA@aetna.com'
       charset: utf8
     tags: mail
     when: root_freespace.stdout|float is lt 2000000

   - name: fail when diskspace threshold is reached
     fail:
       msg: /root does not have the minimum space required to continue (2Gb requested).
     when: root_freespace.stdout|float is lt 2000000

