---
   - name: Check available diskspace on /var partition
     shell: df  /var --output\=avail | tail -1
     register: var_freespace

   - shell: echo "{{ inventory_hostname }}"
     register: op

   - debug:
       msg:
         - "{{ var_freespace.stdout }}"
         - "{{ op.stdout }}"

   - mail:
       subject: 'DISK USAGE ALERT !!!'
       from: 'OnyekachiA@aetna.com'
       body: "/var  HAS REACHED {{ var_freespace.stdout }}  ON {{ op.stdout }}, and does not have the minimum space required to continue (2Gb requested). KINDLY CHECK !!!"
       to: 'OnyekachiA@aetna.com'
       charset: utf8
     tags: mail
     when: var_freespace.stdout|float is lt 2000000

   - name: fail when diskspace threshold is reached
     fail:
       msg: /var does not have the minimum space required to continue (2Gb requested).
     when: var_freespace.stdout|float is lt 2000000


